spring:
  application:
    name: Gate_module

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${GATE_DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    generate-ddl: true
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      group-id: ${MODULE_GROUP_ID}

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/shop
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/shop
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid

keycloak:
  serverUrl: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  username: ${KEYCLOAK_USERNAME}
  password: ${KEYCLOAK_PASSWORD}
  clientId: ${KEYCLOAK_CLIENT_ID}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET}

microservices:
  baseUrl: ${BASE_URL}

web:
  client:
    timeOut: 3000
    retry: 2000
    max-attempts: 3

logging:
  level:
    org.springframework.security: TRACE