spring:
  application:
    name: Gate_module

  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: test

  cache:
    type: none

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/shop
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/shop
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: shop-app-test
            client-secret: 0nKwcagdO62xNuEmjMt2lJms2qzdr2A5
            scope: openid

keycloak:
  serverUrl: http://localhost:8180
  realm: shop
  username: shop-test
  password: test
  clientId: shop-app-test
  clientSecret: 0nKwcagdO62xNuEmjMt2lJms2qzdr2A5

logging:
  level:
    org.springframework.security: TRACE

microservices:
  baseUrl: host.docker.internal

service:
  module-name:
    address: address-service
    order: order-service
    product: product-service
    product-category: product-category-service
    stock: stock-service
    store: store-service
    operation: operation-service
